sudo: required
language: generic

services:
  - docker

before_install:
  - docker-compose build -f docker-compose-dev.yml -p "multi_docker"

script:
  - docker run -e CI=true multi_docker_client_1 npm test

after_success:
  - docker-compose build -p "$DOCKER_ID"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker-compose push
